activation = [["my_module.secret", false], ["another_library.module", true]]
[[handlers]]
sink = "ext://sys.stderr"
format = "[{time}] {message}"

[[handlers]]
sink = "file.log"
enqueue = true
serialize = true

[[levels]]
name = "NEW"
no = 13
icon = "Â¤"
color = ""

[extra]
common_to_all = "default"
